### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by dillfrescott** [prophesier/diff-svc#10]
```
| Binarizer:  <class 'preprocessing.SVCpre.SVCBinarizer'>
spkers:  {'atri'}
| spk_map:  {'atri': 0}
100% 2/2 [00:04<00:00,  2.15s/it]
| valid total duration: 45.280s
100% 2/2 [00:02<00:00,  1.14s/it]
| test total duration: 45.280s
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "preprocessing/binarize.py", line 20, in <module>
    binarize()
  File "preprocessing/binarize.py", line 15, in binarize
    binarizer_cls().process()
  File "/content/diff-svc/preprocessing/base_binarizer.py", line 137, in process
    self.process_data_split('train')
  File "/content/diff-svc/preprocessing/base_binarizer.py", line 175, in process_data_split
    spec_max=np.max(spec_max,0)
  File "<__array_function__ internals>", line 6, in amax
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 2755, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

What does this mean?

**Comment by prophesier** [comment]
it means that your dataset（for training）is empty. maybe you didn't put in enough training data（less than 5）or they were skipped due to other reasons

**Comment by dillfrescott** [comment]
Ohhh OK. Thank you!
