### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by medalawi** [prophesier/diff-svc#29]
I got this error when I run this code on windows

```
 set PYTHONPATH=.
set CUDA_VISIBLE_DEVICES=0 
python preprocessing/binarize.py --config training/config.yaml
```

```
| Binarizer:  <class 'preprocessing.SVCpre.SVCBinarizer'>
Traceback (most recent call last):
  File "preprocessing/binarize.py", line 20, in <module>
    binarize()
  File "preprocessing/binarize.py", line 15, in binarize
    binarizer_cls().process()
  File "C:\Users\ASUS\Downloads\diff-svc\preprocessing\SVCpre.py", line 29, in __init__
    super().__init__(item_attributes)
  File "C:\Users\ASUS\Downloads\diff-svc\preprocessing\base_binarizer.py", line 52, in __init__
    assert all([attr in self.item_attributes for attr in list(self.items.values())[0].keys()])
IndexError: list index out of range
```

**Comment by MUTED64** [comment]
I got this error when I run on Ubuntu 22.04 LTS too.
