### ISSUE TITLE
 cannot import name 'consume_prefix_in_state_dict_if_present' from 'torch.nn.modules.utils'

### ISSUE THREAD

**Issue by FlashlightET** [prophesier/diff-svc#71]
nobody in the universe has had this happen to them, requirements.txt is incomplete and i still have to install 300 more modules that have errors just to use this with no luck.
```
Traceback (most recent call last):
  File "infer.py", line 9, in <module>
    from infer_tools import infer_tool
  File "x:\diffsvc\diff-svc\infer_tools\infer_tool.py", line 20, in <module>
    from preprocessing.hubertinfer import Hubertencoder
  File "x:\diffsvc\diff-svc\preprocessing\hubertinfer.py", line 8, in <module>
    from network.hubert.hubert_model import hubert_soft, get_units
  File "x:\diffsvc\diff-svc\network\hubert\hubert_model.py", line 11, in <module>
    from torch.nn.modules.utils import consume_prefix_in_state_dict_if_present
ImportError: cannot import name 'consume_prefix_in_state_dict_if_present' from 'torch.nn.modules.utils' (C:\Users\EzoGaming\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\utils.py)
```

**Comment by FlashlightET** [comment]
I WAS IN THE WRONG ENVIRONMENT
