### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PitchExtractor:

### ISSUE THREAD

**Issue by FlashlightET** [prophesier/diff-svc#72]
```
(diffsvc) x:\diffsvc\diff-svc>python infer.py
| load 'model' from './checkpoints/model/model_ckpt_steps_600000.ckpt'.
Traceback (most recent call last):
  File "infer.py", line 93, in <module>
    model = Svc(project_name, config_path, hubert_gpu, model_path)
  File "x:\diffsvc\diff-svc\infer_tools\infer_tool.py", line 135, in __init__
    utils.load_ckpt(self.pe, hparams['pe_ckpt'], 'model', strict=True)
  File "x:\diffsvc\diff-svc\utils\__init__.py", line 202, in load_ckpt
    cur_model.load_state_dict(state_dict, strict=strict)
  File "C:\Users\EzoGaming\anaconda3\envs\diffsvc\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PitchExtractor:
        Missing key(s) in state_dict: "mel_prenet.layers.0.0.weight", "mel_prenet.layers.0.0.bias", "mel_prenet.layers.0.2.weight", "mel_prenet.layers.0.2.bias", "mel_prenet.layers.0.2.running_mean", "mel_prenet.layers.0.2.running_var", "mel_prenet.layers.1.0.weight", "mel_prenet.layers.1.0.bias", "mel_prenet.layers.1.2.weight", "mel_prenet.layers.1.2.bias", "mel_prenet.layers.1.2.running_mean", "mel_prenet.layers.1.2.running_var",
...
```

**Comment by i3l3** [comment]
I have a same issue, too.
