### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dillfrescott** [prophesier/diff-svc#9]
```
| Hparams chains:  ['training/config.yaml']
| Hparams: 
;33;mK_step: 1000, ;33;maccumulate_grad_batches: 1, ;33;maudio_num_mel_bins: 80, ;33;maudio_sample_rate: 24000, ;33;mbinarization_args: {'shuffle': False, 'with_align': True, 'with_f0': True, 'with_hubert': True, 'with_spk_embed': False, 'with_wav': False}, 
;33;mbinarizer_cls: preprocessing.SVCpre.SVCBinarizer, ;33;mbinary_data_dir: data/binary/atri, ;33;mcheck_val_every_n_epoch: 10, ;33;mchoose_test_manually: False, ;33;mclip_grad_norm: 1, 
;33;mconfig_path: training/config.yaml, ;33;mcontent_cond_steps: [], ;33;mcwt_add_f0_loss: False, ;33;mcwt_hidden_size: 128, ;33;mcwt_layers: 2, 
;33;mcwt_loss: l1, ;33;mcwt_std_scale: 0.8, ;33;mdatasets: ['opencpop'], ;33;mdebug: False, ;33;mdec_ffn_kernel_size: 9, 
;33;mdec_layers: 4, ;33;mdecay_steps: 40000, ;33;mdecoder_type: fft, ;33;mdict_dir: , ;33;mdiff_decoder_type: wavenet, 
;33;mdiff_loss_type: l2, ;33;mdilation_cycle_length: 4, ;33;mdropout: 0.1, ;33;mds_workers: 4, ;33;mdur_enc_hidden_stride_kernel: ['0,2,3', '0,2,3', '0,1,3'], 
;33;mdur_loss: mse, ;33;mdur_predictor_kernel: 3, ;33;mdur_predictor_layers: 5, ;33;menc_ffn_kernel_size: 9, ;33;menc_layers: 4, 
;33;mencoder_K: 8, ;33;mencoder_type: fft, ;33;mendless_ds: False, ;33;mf0_bin: 256, ;33;mf0_max: 1100.0, 
;33;mf0_min: 50.0, ;33;mffn_act: gelu, ;33;mffn_padding: SAME, ;33;mfft_size: 512, ;33;mfmax: 12000, 
;33;mfmin: 30, ;33;mfs2_ckpt: , ;33;mgaussian_start: True, ;33;mgen_dir_name: , ;33;mgen_tgt_spk_id: -1, 
;33;mhidden_size: 256, ;33;mhop_size: 128, ;33;mhubert_gpu: True, ;33;mhubert_path: checkpoints/hubert/hubert_soft.pt, ;33;minfer: False, 
;33;mkeep_bins: 80, ;33;mlambda_commit: 0.25, ;33;mlambda_energy: 0.0, ;33;mlambda_f0: 1.0, ;33;mlambda_ph_dur: 0.3, 
;33;mlambda_sent_dur: 1.0, ;33;mlambda_uv: 1.0, ;33;mlambda_word_dur: 1.0, ;33;mload_ckpt: , ;33;mlog_interval: 100, 
;33;mloud_norm: False, ;33;mlr: 0.0004, ;33;mmax_beta: 0.02, ;33;mmax_epochs: 3000, ;33;mmax_eval_sentences: 1, 
;33;mmax_eval_tokens: 60000, ;33;mmax_frames: 42000, ;33;mmax_input_tokens: 6000, ;33;mmax_sentences: 88, ;33;mmax_tokens: 128000, 
;33;mmax_updates: 1000000, ;33;mmel_loss: ssim:0.5|l1:0.5, ;33;mmel_vmax: 1.5, ;33;mmel_vmin: -6.0, ;33;mmin_level_db: -120, 
;33;mnorm_type: gn, ;33;mnum_ckpt_keep: 10, ;33;mnum_heads: 2, ;33;mnum_sanity_val_steps: 1, ;33;mnum_spk: 1, 
;33;mnum_test_samples: 0, ;33;mnum_valid_plots: 10, ;33;moptimizer_adam_beta1: 0.9, ;33;moptimizer_adam_beta2: 0.98, ;33;mout_wav_norm: False, 
;33;mpe_ckpt: checkpoints/0102_xiaoma_pe/model_ckpt_steps_60000.ckpt, ;33;mpe_enable: False, ;33;mperform_enhance: True, ;33;mpitch_ar: False, ;33;mpitch_enc_hidden_stride_kernel: ['0,2,5', '0,2,5', '0,2,5'], 
;33;mpitch_extractor: parselmouth, ;33;mpitch_loss: l2, ;33;mpitch_norm: log, ;33;mpitch_type: frame, ;33;mpndm_speedup: 10, 
;33;mpre_align_args: {'allow_no_txt': False, 'denoise': False, 'forced_align': 'mfa', 'txt_processor': 'zh_g2pM', 'use_sox': True, 'use_tone': False}, ;33;mpre_align_cls: data_gen.singing.pre_align.SingingPreAlign, ;33;mpredictor_dropout: 0.5, ;33;mpredictor_grad: 0.1, ;33;mpredictor_hidden: -1, 
;33;mpredictor_kernel: 5, ;33;mpredictor_layers: 5, ;33;mprenet_dropout: 0.5, ;33;mprenet_hidden_size: 256, ;33;mpretrain_fs_ckpt: , 
;33;mprocessed_data_dir: xxx, ;33;mprofile_infer: False, ;33;mraw_data_dir: data/raw/atri, ;33;mref_norm_layer: bn, ;33;mrel_pos: True, 
;33;mreset_phone_dict: True, ;33;mresidual_channels: 256, ;33;mresidual_layers: 20, ;33;msave_best: False, ;33;msave_ckpt: True, 
;33;msave_codes: ['configs', 'modules', 'src', 'utils'], ;33;msave_f0: True, ;33;msave_gt: False, ;33;mschedule_type: linear, ;33;mseed: 1234, 
;33;msort_by_len: True, ;33;mspeaker_id: atri, ;33;mspec_max: [-1.5451143980026245, -1.5177826881408691, -1.1807013750076294, -0.6732071042060852, -0.47006210684776306, -0.271837055683136, -0.27174147963523865, -0.3395537734031677, -0.2529868483543396, -0.22453370690345764, -0.24767500162124634, -0.22861438989639282, -0.28668588399887085, -0.335957795381546, -0.3118636906147003, -0.34530898928642273, -0.35274678468704224, -0.4730182886123657, -0.45395755767822266, -0.4338522255420685, -0.41395917534828186, -0.29468369483947754, -0.16852207481861115, -0.3900046646595001, -0.6241626739501953, -0.5899035930633545, -0.6534764170646667, -0.6667397022247314, -0.6992383003234863, -0.7867978811264038, -0.8457596302032471, -0.43350857496261597, -0.629216730594635, -0.9135912656784058, -0.9230040311813354, -0.6756577491760254, -0.8399246335029602, -0.8495144248008728, -0.781493067741394, -1.0347247123718262, -1.0051935911178589, -1.1246198415756226, -1.021154522895813, -0.851677417755127, -0.8443652987480164, -0.9016147255897522, -0.7618780732154846, -1.0490750074386597, -1.2046996355056763, -1.2022035121917725, -0.9753153324127197, -1.2503044605255127, -1.0664823055267334, -1.1236635446548462, -1.2223032712936401, -1.0116488933563232, -1.2263423204421997, -1.2552075386047363, -1.3846945762634277, -1.2681812047958374, -1.3416036367416382, -1.264938235282898, -1.2763726711273193, -1.4651004076004028, -1.4880361557006836, -1.5735552310943604, -1.4097294807434082, -1.468385100364685, -1.3768259286880493, -1.3312186002731323, -1.3547866344451904, -1.4387739896774292, -1.1861546039581299, -1.1709729433059692, -1.1812609434127808, -1.1489264965057373, -1.5605546236038208, -2.2702553272247314, -4.064557075500488, -5.809507846832275], ;33;mspec_min: [-5.740882873535156, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.959110260009766, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.999546527862549, -6.0, -5.995517730712891, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -5.960205078125, -5.93423318862915, -6.0, -5.933608531951904, -6.0, -6.0, -6.0, -5.953958511352539, -5.908934593200684, -5.911312580108643, -5.882552623748779, -5.932425498962402, -5.91495943069458, -5.826524257659912, -5.777952671051025, -5.775007724761963, -5.849961280822754, -5.7793660163879395, -5.781087875366211, -5.818603992462158, -5.765895366668701, -5.834509372711182, -5.817623615264893, -5.855445384979248, -5.844409465789795, -5.760529518127441, -5.713063716888428, -5.74588680267334, -5.855954647064209, -5.874588489532471, -5.81571626663208, -5.849369049072266, -5.963766574859619, -5.8541646003723145, -5.922942161560059, -6.0, -6.0, -6.0, -6.0], ;33;mspk_cond_steps: [], 
;33;mstop_token_weight: 5.0, ;33;mtask_cls: training.task.SVC_task.SVCTask, ;33;mtest_ids: [], ;33;mtest_input_dir: , ;33;mtest_num: 0, 
;33;mtest_prefixes: ['test'], ;33;mtest_set_name: test, ;33;mtimesteps: 1000, ;33;mtrain_set_name: train, ;33;muse_crepe: False, 
;33;muse_denoise: False, ;33;muse_energy_embed: False, ;33;muse_gt_dur: False, ;33;muse_gt_f0: False, ;33;muse_midi: False, 
;33;muse_nsf: True, ;33;muse_pitch_embed: True, ;33;muse_pos_embed: True, ;33;muse_spk_embed: False, ;33;muse_spk_id: False, 
;33;muse_split_spk_id: False, ;33;muse_uv: True, ;33;muse_var_enc: False, ;33;mval_check_interval: 2000, ;33;mvalid_num: 0, 
;33;mvalid_set_name: valid, ;33;mvalidate: False, ;33;mvocoder: network.vocoders.hifigan.HifiGAN, ;33;mvocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128, ;33;mwarmup_updates: 2000, 
;33;mwav2spec_eps: 1e-6, ;33;mweight_decay: 0, ;33;mwin_size: 512, ;33;mwork_dir: , 
| Binarizer:  <class 'preprocessing.SVCpre.SVCBinarizer'>
Traceback (most recent call last):
  File "preprocessing/binarize.py", line 20, in <module>
    binarize()
  File "preprocessing/binarize.py", line 15, in binarize
    binarizer_cls().process()
  File "/content/diff-svc/preprocessing/SVCpre.py", line 29, in __init__
    super().__init__(item_attributes)
  File "/content/diff-svc/preprocessing/base_binarizer.py", line 52, in __init__
    assert all([attr in self.item_attributes for attr in list(self.items.values())[0].keys()])
IndexError: list index out of range
```

**Comment by prophesier** [comment]
It seems that you didn't put your data in raw_data_dir, but i'm not quite sure about it.

**Comment by dillfrescott** [comment]
I thought I did that but I can try again in a while. Thank you

**Comment by dillfrescott** [comment]
I think it was because I was missing the checkpoint models. I will close this issue.
